childrens_holidays/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
]

main/urls.py
from django.urls import path
from . import views


app_name='main' 

urlpatterns = [
    path('aboutus/', views.aboutus, name='aboutus'),
    path('holiday/', views.holiday, name='holiday'),
    path('howto/', views.howto, name='howto'),
    path('', views.index, name='index'),
    path('programs/', views.programs, name='programs'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


app_name='users' 

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('delete_order/<int:order_id>', views.delete_order, name='delete_order'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from users.models import User

# Create your models here.
class Orders(models.Model):
    user_id = models.ForeignKey(User, verbose_name='Заказчик', on_delete=models.PROTECT)
    order_description = models.CharField(max_length=150)

    def __str__(self):
        return f'{self.user_id}|{self.order_description}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class Application(models.Model):
    user_id = models.ForeignKey(User, verbose_name='Заказчик', on_delete=models.PROTECT)
    customer_name = models.CharField(max_length=100)
    customer_number = models.CharField(max_length=20)


    def __str__(self):
        return f'{self.user_id}|{self.customer_name}|{self.customer_number}'

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'


class Catalogs(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = 'Каталог'

class Order_info(models.Model):
    order_id = models.ForeignKey(Orders, verbose_name='Заказ', on_delete=models.PROTECT)
    catalog_id = models.ForeignKey(Catalogs, verbose_name='Программы', on_delete=models.PROTECT)
    quantity = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = 'Информация о заказах'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

main/forms.py
from django import forms

from .models import Application

class UserCreateApplicationForm(forms.ModelForm):
    customer_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'clearble form-control', 'placeholder': 'Ваше имя', 'style': 'margin-top: 20px;', 'size': '20'
    }))
    customer_number = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'clearble form-control ', 'placeholder': 'Ваш телефон', 'style': 'margin-top: 15px;', 'size': '20'
    }))
    
    
    class Meta:
        model = Application
        fields = ("customer_name", "customer_number")

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'id': "username", 'placeholder': 'Почта'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password', 'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Почта'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password', 'placeholder': 'Пароль'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'id': 'password', 'placeholder': 'Повторите пароль'
    }))
    

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
        

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
        'class': 'form-control'
    }),
        required=False)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
        'class': 'form-control'
    }),
        required=False)
    image = forms.ImageField(widget=forms.FileInput(
        attrs={'class': 'custom-file-input',
               'id': 'image-upload',
               }),
        required=False
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image')

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import UserCreateApplicationForm
from django.contrib import messages

# Create your views here.
def aboutus(request):
    return render(request, 'main/aboutus.html')

def holiday(request):
    return render(request, 'main/holiday.html')

def howto(request):
    return render(request, 'main/howto.html')

def index(request):
    if request.method == "POST":
        form = UserCreateApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user_id = request.user
            messages.success(request, 'Вы успешно зарегистрировали заявку!')
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = UserCreateApplicationForm()


    context = {
        'form': UserCreateApplicationForm
    }
    return render(request, 'main/index.html', context)

def mastets(request):
    return render(request, 'main/mastets.html')

def programs(request):
    return render(request, 'main/programs.html')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from main.models import Orders


def login(request):
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context={
        'form': form,
        'title': 'Login'
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
        'title': 'Registration'
    }
    return render(request, 'users/registration.html', context)

def profile(request):
    if request.method == 'POST':
        print(request.POST)
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    orders = Orders.objects.filter(user_id = request.user.id)
    context = {
        'form': form,
        'title': 'Profile',
        'orders': orders
    }
    return render(request, 'users/profile.html', context)


def delete_order(request, order_id):
    order = Orders.objects.get(id=order_id)
    if order.user_id == request.user:
        order.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

main/templates/main/aboutus.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

     <meta charset="utf-8">
    <title>Праздики</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'main/css/bootstrap.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/style.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/jquery.countdown.css'%}" rel="stylesheet" type="text/css"> 
<!-- <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-5572139489027959",
          enable_page_level_ads: true
     });
</script>
    <!-- JavaScript plugins (requires jQuery) -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.countdown.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.countdown-ru.js'%}"></script>

<!--[if IE 7]>
    <link rel="stylesheet" href="assets/font/phone-ie7.css"><![endif]-->

<!-- О компании -->  
<body>
<div class="menu">
    <p class="inmenu">
        <a href="{% url 'main:index'%}">Главная</a>
        <a href="{% url 'main:aboutus'%}">Наши преимущества</a>
        <a href="{% url 'main:howto'%}">Порядок работы</a>
        <a href="{% url 'main:programs'%}">Программы</a>
        <a href="{% url 'main:holiday'%}">Наши праздники</a>
    </p>
</div>
<div class="about-us">
    <div class="container">
      <div class="row text-center" style="font-size:19px">
          <div class="headin1">
              <h1><span class="borbotred">НАШИ ПРЕИМУЩЕСТВА:</span></h1>
          </div>    
          <div class="col-4">
              <img src="{% static 'main/img/eggs/1'%}.png" height="142" width="auto" style="margin-bottom:8px">
              <p><b>У нас работают<br>профессионалы!</b></p>
              <p>Все аниматоры - актеры<br>лучших театров<br>опытом работы более 7 лет</p>
          </div>
          <div class="col-4">
              <img src="{% static 'main/img/eggs/2'%}.png" height="125" width="auto" style="margin-bottom:25px">
                 <p><b>Индивидуальный подход<br>к каждому вашему ребенку!</b></p>
              <p>Разработка уникальных<br>сценариев под увлечения<br>и возраст ребенка</p>
          </div>
          <div class="col-4">
              <img src="{% static 'main/img/eggs/3'%}.png" height="112" width="auto" style="margin-bottom:19px; margin-top:19px">
               <p><b>Персонажи любимых книг<br>и мультфильмов!</b></p>
              <p>У нас своя собственная<br>костюмерная, насчитывающая<br>более 200 качественных<br>костюмов, привезенных из США</p>
          </div>
    </div>    
      <div class="row text-center" style="font-size:19px; margin:60px 0">
          <div class="col-1"></div>
          <div class="col-5" style="margin:0 -30px 0 30px">
              <img src="{% static 'main/img/eggs/4'%}.png" height="99" width="auto" style="margin-bottom:13px">
                 <p><b>Мы работаем - Вы отдыхаете!</b></p>
              <p>Организация детского праздника<br>под ключ: от подбора площадки<br>до праздничного торта</p>
          </div>
          <div class="col-5" style="margin:0 30px 0 -30px">
              <img src="{% static 'main/img/eggs/5'%}.png" height="102"  width="auto" style="margin-bottom:10px;">
               <p><b>Не торопитесь платить!</b></p>
              <p>Оплата услуг без предоплаты,<br>по факту</p>
          </div>
        </div>    
  </div>
</div>
<div style="background-color:rgb(178,30,182); height:35px; min-width:1024px; box-shadow:0 15px 20px rgba(0,0,0,.3)"></div>        
<!-- О компании -->  
    <!-- Первый экран -->   
    <div class="underheader"> 
        <div class="header">
               <div class="container">
                       <div class="row">
                        <div class="col-4">
                            <img src="{% static 'main/img/logo.png'%}" style="margin-top:-42px">
                        </div>
                        <div class="col-4">
                            <p style="margin: 40px 0 0 -50px;">Кампания<br>ИНН <br>КПП </p>
                            <a style="color:#9e0067; cursor: default;" href="https://web-exito.ru/shablony-landing-page/" target="_blank">Скачать шаблоны сайтов - Web-exito.ru</a>
                        </div>
                            <div class="col-4 text-right">
                                  <p style="font-size:32px; padding-top:45px;padding-right: 20px;">+7(800)000-00-00</p>
                               <p style="padding-right: 20px;">Часы работы: 10:00 - 22:00</p>
                       </div>
                  </div>
            </div>
       </div>
       </div>
         <!-- ====================== MODAL ================= -->  
         <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                           <div class="forma" style="">
                              <div id="note3"></div>
                                  <div id="fields3">
                                       <p><span class="borbotred" style="font-size:25px">ОСТАВЬТЕ ЗАЯВКУ</span><br><br><span data-toogle="popover" data-content="Введите телефон"  style="font-size:19px">и наши менеджеры<br>бесплатно пришлют<br>Вам полный список<br>наших программ</span><br></p>
                                      <form action="index1.php" method="Post">
                                           <input class="clearble form-control" name="name" type="text" size="20" placeholder="Ваше имя" style="margin-top: 20px;">
                                        <input data-toogle="popover" data-content="Введите данные" data-placement="top"  id="inp3" class="clearble form-control" name="phone" type="text" size="20" placeholder="Ваш телефон" style="margin-top: 15px;">
                                        <input required class="btn btn-red" type="submit" value="ЗАКАЗАТЬ">
                                         </form>
                                   </div>
                         </div>
           </div> 
           <!-- ====================== MODAL ================= -->
   
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="{% static 'main/js/bootstrap.min.js'%}"></script>
      <script src="{% static 'main/js/contact.js'%}"></script>
   <!-- Enable responsive features in IE8 with Respond.js (https://github.com/scottjehl/Respond) -->
       <!--<script src="assets/js/respond.js"></script>-->
     </body>
   </html>

main/templates/main/holiday.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

     <meta charset="utf-8">
    <title>Праздики</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'main/css/bootstrap.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/style.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/jquery.countdown.css'%}" rel="stylesheet" type="text/css"> 
<!-- <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-5572139489027959",
          enable_page_level_ads: true
     });
</script>
    <!-- JavaScript plugins (requires jQuery) -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.countdown.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.countdown-ru.js'%}"></script>

<!--[if IE 7]>
    <link rel="stylesheet" href="assets/font/phone-ie7.css"><![endif]-->

<!-- О компании -->  
<body>
<div class="menu">
    <p class="inmenu">
        <a href="{% url 'main:index'%}">Главная</a>
        <a href="{% url 'main:aboutus'%}">Наши преимущества</a>
        <a href="{% url 'main:howto'%}">Порядок работы</a>
        <a href="{% url 'main:programs'%}">Программы</a>
        <a href="{% url 'main:holiday'%}">Наши праздники</a>
    </p>
</div>
<div class="row text-center" style=" margin:30px 0 70px">
    <div style="margin-bottom:30px">
        <h1 style="color: #bc2e88;">НАШИ ПРАЗДНИКИ</h1>
    </div>    
    <div class="col-6" style="padding:25px">
        <img src="{% static 'main/img/ourworks/1.jpg'%}" style="margin-left: -23px;">
     </div>   
    <div class="col-6" style="padding:25px">
        <img src="{% static 'main/img/ourworks/2.jpg'%}" style="margin-right: -23px;">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/3.jpg'%}">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/4.jpg'%}">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/5.jpg'%}">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/6.jpg'%}">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/7.jpg'%}">
     </div>   
    <div class="col-4" style="padding:30px">
        <img src="{% static 'main/img/ourworks/8.jpg'%}">
     </div>   
</div>
</div>
</div>     
    <!-- Первый экран -->   
    <div class="underheader"> 
        <div class="header">
               <div class="container">
                       <div class="row">
                        <div class="col-4">
                            <img src="{% static 'main/img/logo.png'%}" style="margin-top:-42px">
                        </div>
                        <div class="col-4">
                            <p style="margin: 40px 0 0 -50px;">Кампания<br>ИНН <br>КПП </p>
                            <a style="color:#9e0067; cursor: default;" href="https://web-exito.ru/shablony-landing-page/" target="_blank">Скачать шаблоны сайтов - Web-exito.ru</a>
                        </div>
                            <div class="col-4 text-right">
                                  <p style="font-size:32px; padding-top:45px;padding-right: 20px;">+7(800)000-00-00</p>
                               <p style="padding-right: 20px;">Часы работы: 10:00 - 22:00</p>
                       </div>
                  </div>
            </div>
       </div>
       </div>
         <!-- ====================== MODAL ================= -->  
         <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                           <div class="forma" style="">
                              <div id="note3"></div>
                                  <div id="fields3">
                                       <p><span class="borbotred" style="font-size:25px">ОСТАВЬТЕ ЗАЯВКУ</span><br><br><span data-toogle="popover" data-content="Введите телефон"  style="font-size:19px">и наши менеджеры<br>бесплатно пришлют<br>Вам полный список<br>наших программ</span><br></p>
                                      <form action="index1.php" method="Post">
                                           <input class="clearble form-control" name="name" type="text" size="20" placeholder="Ваше имя" style="margin-top: 20px;">
                                        <input data-toogle="popover" data-content="Введите данные" data-placement="top"  id="inp3" class="clearble form-control" name="phone" type="text" size="20" placeholder="Ваш телефон" style="margin-top: 15px;">
                                        <input required class="btn btn-red" type="submit" value="ЗАКАЗАТЬ">
                                         </form>
                                   </div>
                         </div>
           </div> 
           <!-- ====================== MODAL ================= -->
   
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="{% static 'main/js/bootstrap.min.js'%}"></script>
      <script src="{% static 'main/js/contact.js'%}"></script>
   <!-- Enable responsive features in IE8 with Respond.js (https://github.com/scottjehl/Respond) -->
       <!--<script src="assets/js/respond.js"></script>-->
     </body>
   </html>

main/templates/main/howto.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

     <meta charset="utf-8">
    <title>Праздики</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{% static 'main/css/bootstrap.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/style.css'%}" rel="stylesheet" media="screen">
    <link href="{% static 'main/css/jquery.countdown.css'%}" rel="stylesheet" type="text/css"> 
<!-- <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> -->
<script>
     (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-5572139489027959",
          enable_page_level_ads: true
     });
</script>
    <!-- JavaScript plugins (requires jQuery) -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.countdown.min.js'%}"></script>
	<script type="text/javascript" src="{% static 'main/js/jquery.countdown-ru.js'%}"></script>

<!--[if IE 7]>
    <link rel="stylesheet" href="assets/font/phone-ie7.css"><![endif]-->

<!-- О компании -->  
<body>
<div class="menu">
    <p class="inmenu">
        <a href="{% url 'main:index'%}">Главная</a>
        <a href="{% url 'main:aboutus'%}">Наши преимущества</a>
        <a href="{% url 'main:howto'%}">Порядок работы</a>
        <a href="{% url 'main:programs'%}">Программы</a>
        <a href="{% url 'main:holiday'%}">Наши праздники</a>
    </p>
</div>
<div class="how-we">
    <div class="container">
      <div class="row text-center" style=" margin:30px 0; position:relative">
          <div style="margin-bottom:50px">
              <h1 style="color:#fff;">КАК МЫ РАБОТАЕМ</h1>
          </div>    
          <img src="{% static 'main/img/how.png'%}" width="947" height="293">
          <p class="pinhow" style="left:50px">Вы оставляете<br>заявку на сайте</p>
          <p class="pinhow" style="top:430px; left:220px">Менеджер уточняет<br>детали Вашего заказа</p>
          <p class="pinhow" style="left:445px">Мы утверждаем<br>смету</p>
          <p class="pinhow" style="top:430px; right:250px">Оплата по факту<br>проведения</p>
          <p class="pinhow" style="right:15px">Ваш ребенок<br>постояно вспоминает<br>этот волшебный день</p>
      </div>
  </div>
</div> 
    <!-- Первый экран -->   
    <div class="underheader"> 
        <div class="header">
               <div class="container">
                       <div class="row">
                        <div class="col-4">
                            <img src="{% static 'main/img/logo.png'%}" style="margin-top:-42px">
                        </div>
                        <div class="col-4">
                            <p style="margin: 40px 0 0 -50px;">Кампания<br>ИНН <br>КПП </p>
                            <a style="color:#9e0067; cursor: default;" href="https://web-exito.ru/shablony-landing-page/" target="_blank">Скачать шаблоны сайтов - Web-exito.ru</a>
                        </div>
                            <div class="col-4 text-right">
                                  <p style="font-size:32px; padding-top:45px;padding-right: 20px;">+7(800)000-00-00</p>
                               <p style="padding-right: 20px;">Часы работы: 10:00 - 22:00</p>
                       </div>
                  </div>
            </div>
       </div>
       </div>
         <!-- ====================== MODAL ================= -->  
         <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                           <div class="forma" style="">
                              <div id="note3"></div>
                                  <div id="fields3">
                                       <p><span class="borbotred" style="font-size:25px">ОСТАВЬТЕ ЗАЯВКУ</span><br><br><span data-toogle="popover" data-content="Введите телефон"  style="font-size:19px">и наши менеджеры<br>бесплатно пришлют<br>Вам полный список<br>наших программ</span><br></p>
                                      <form action="index1.php" method="POST">
                                           <input class="clearble form-control" name="name" type="text" size="20" placeholder="Ваше имя" style="margin-top: 20px;">
                                        <input data-toogle="popover" data-content="Введите данные" data-placement="top"  id="inp3" class="clearble form-control" name="phone" type="text" size="20" placeholder="Ваш телефон" style="margin-top: 15px;">
                                        <input required class="btn btn-red" type="submit" value="ЗАКАЗАТЬ">
                                         </form>
                                   </div>
                         </div>
           </div> 
           <!-- ====================== MODAL ================= -->
   
      <!-- Include all compiled plugins (below), or include individual files as needed -->
       <script src="{% static 'main/js/bootstrap.min.js'%}"></script>
       <script src="{% static 'main/js/contact.js'%}"></script>
   <!-- Enable responsive features in IE8 with Respond.js (https://github.com/scottjehl/Respond) -->
       <!--<script src="assets/js/respond.js"></script>-->
     </body>
   </html>